//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPI_Diagramador.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TPI_Diagramador.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_relleno_amarillo {
            get {
                object obj = ResourceManager.GetObject("circulo_relleno_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_relleno_celeste {
            get {
                object obj = ResourceManager.GetObject("circulo_relleno_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_relleno_morado {
            get {
                object obj = ResourceManager.GetObject("circulo_relleno_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_relleno_naranja {
            get {
                object obj = ResourceManager.GetObject("circulo_relleno_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_relleno_negro {
            get {
                object obj = ResourceManager.GetObject("circulo_relleno_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_relleno_rojo {
            get {
                object obj = ResourceManager.GetObject("circulo_relleno_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_relleno_verde {
            get {
                object obj = ResourceManager.GetObject("circulo_relleno_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_vacio_amarillo {
            get {
                object obj = ResourceManager.GetObject("circulo_vacio_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_vacio_celeste {
            get {
                object obj = ResourceManager.GetObject("circulo_vacio_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_vacio_morado {
            get {
                object obj = ResourceManager.GetObject("circulo_vacio_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_vacio_naranja {
            get {
                object obj = ResourceManager.GetObject("circulo_vacio_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_vacio_negro {
            get {
                object obj = ResourceManager.GetObject("circulo_vacio_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_vacio_negro1 {
            get {
                object obj = ResourceManager.GetObject("circulo_vacio_negro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_vacio_rojo {
            get {
                object obj = ResourceManager.GetObject("circulo_vacio_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circulo_vacio_verde {
            get {
                object obj = ResourceManager.GetObject("circulo_vacio_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_relleno_amarillo {
            get {
                object obj = ResourceManager.GetObject("cuadrado_relleno_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_relleno_celeste {
            get {
                object obj = ResourceManager.GetObject("cuadrado_relleno_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_relleno_morado {
            get {
                object obj = ResourceManager.GetObject("cuadrado_relleno_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_relleno_naranja {
            get {
                object obj = ResourceManager.GetObject("cuadrado_relleno_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_relleno_negro {
            get {
                object obj = ResourceManager.GetObject("cuadrado_relleno_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_relleno_rojo {
            get {
                object obj = ResourceManager.GetObject("cuadrado_relleno_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_relleno_verde {
            get {
                object obj = ResourceManager.GetObject("cuadrado_relleno_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_vacio_amarillo {
            get {
                object obj = ResourceManager.GetObject("cuadrado_vacio_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_vacio_celeste {
            get {
                object obj = ResourceManager.GetObject("cuadrado_vacio_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_vacio_morado {
            get {
                object obj = ResourceManager.GetObject("cuadrado_vacio_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_vacio_naranja {
            get {
                object obj = ResourceManager.GetObject("cuadrado_vacio_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_vacio_negro {
            get {
                object obj = ResourceManager.GetObject("cuadrado_vacio_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_vacio_negro1 {
            get {
                object obj = ResourceManager.GetObject("cuadrado_vacio_negro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_vacio_rojo {
            get {
                object obj = ResourceManager.GetObject("cuadrado_vacio_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuadrado_vacio_verde {
            get {
                object obj = ResourceManager.GetObject("cuadrado_vacio_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_abajo_amarillo {
            get {
                object obj = ResourceManager.GetObject("flecha_abajo_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_abajo_celeste {
            get {
                object obj = ResourceManager.GetObject("flecha_abajo_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_abajo_morado {
            get {
                object obj = ResourceManager.GetObject("flecha_abajo_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_abajo_naranja {
            get {
                object obj = ResourceManager.GetObject("flecha_abajo_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_abajo_negra {
            get {
                object obj = ResourceManager.GetObject("flecha_abajo_negra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_abajo_rojo {
            get {
                object obj = ResourceManager.GetObject("flecha_abajo_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_abajo_rojo1 {
            get {
                object obj = ResourceManager.GetObject("flecha_abajo_rojo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_abajo_verde {
            get {
                object obj = ResourceManager.GetObject("flecha_abajo_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_arriba_amarillo {
            get {
                object obj = ResourceManager.GetObject("flecha_arriba_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_arriba_celeste {
            get {
                object obj = ResourceManager.GetObject("flecha_arriba_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_arriba_morado {
            get {
                object obj = ResourceManager.GetObject("flecha_arriba_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_arriba_naranja {
            get {
                object obj = ResourceManager.GetObject("flecha_arriba_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_arriba_negra {
            get {
                object obj = ResourceManager.GetObject("flecha_arriba_negra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_arriba_rojo {
            get {
                object obj = ResourceManager.GetObject("flecha_arriba_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_arriba_rojo1 {
            get {
                object obj = ResourceManager.GetObject("flecha_arriba_rojo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_arriba_verde {
            get {
                object obj = ResourceManager.GetObject("flecha_arriba_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_amarilla {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_amarilla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_amarilla1 {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_amarilla1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_celeste {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_celeste1 {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_celeste1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_morada {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_morada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_morada1 {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_morada1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_naranja {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_naranja1 {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_naranja1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_negra {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_negra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_negra1 {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_negra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_roja {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_roja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_roja1 {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_roja1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_verde {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_derecha_verde1 {
            get {
                object obj = ResourceManager.GetObject("flecha_derecha_verde1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_amarilla {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_amarilla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_amarilla1 {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_amarilla1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_celeste {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_celeste___copia__2_ {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_celeste - copia (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_celeste___copia__2_1 {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_celeste - copia (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_celeste1 {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_celeste1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_morada {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_morada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_morada1 {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_morada1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_naranja {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_naranja1 {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_naranja1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_negra {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_negra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_negra1 {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_negra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_negra2 {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_negra2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_roja {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_roja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_roja1 {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_roja1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_verde {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flecha_izquierda_verde1 {
            get {
                object obj = ResourceManager.GetObject("flecha_izquierda_verde1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_amarillo {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_amarillo1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_amarillo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_celeste {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_celeste1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_celeste1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_morado {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_morado1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_morado1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_naranja {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_naranja1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_naranja1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_negra {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_negra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_negra1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_negra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_rojo {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_rojo1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_rojo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_verde {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_derecha_verde1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_derecha_verde1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_amarillo {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_amarillo1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_amarillo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_celeste {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_celeste1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_celeste1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_morado {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_morado1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_morado1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_naranja {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_naranja1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_naranja1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_negra {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_negra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_negra1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_negra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_rojo {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_rojo1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_rojo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_verde {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_abajo_izquierda_verde1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_abajo_izquierda_verde1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_amarilla {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_amarilla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_amarilla1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_amarilla1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_celeste {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_celeste1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_celeste1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_morado {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_morado1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_morado1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_naranja {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_naranja1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_naranja1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_negra {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_negra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_negra1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_negra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_rojo {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_rojo1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_rojo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_verde {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_derecha_verde1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_derecha_verde1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_amarillo {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_amarillo1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_amarillo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_celeste {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_celeste1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_celeste1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_morado {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_morado1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_morado1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_naranja {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_naranja1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_naranja1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_negra {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_negra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_negra1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_negra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_rojo {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_rojo1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_rojo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_verde {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flechaD_arriba_izquierda_verde1 {
            get {
                object obj = ResourceManager.GetObject("flechaD_arriba_izquierda_verde1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_horizontal_amarillo {
            get {
                object obj = ResourceManager.GetObject("linea_horizontal_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_horizontal_celeste {
            get {
                object obj = ResourceManager.GetObject("linea_horizontal_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_horizontal_morado {
            get {
                object obj = ResourceManager.GetObject("linea_horizontal_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_horizontal_naranja {
            get {
                object obj = ResourceManager.GetObject("linea_horizontal_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_horizontal_negra {
            get {
                object obj = ResourceManager.GetObject("linea_horizontal_negra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_horizontal_negra1 {
            get {
                object obj = ResourceManager.GetObject("linea_horizontal_negra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_horizontal_roja {
            get {
                object obj = ResourceManager.GetObject("linea_horizontal_roja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_horizontal_verde {
            get {
                object obj = ResourceManager.GetObject("linea_horizontal_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_vertical_amarillo {
            get {
                object obj = ResourceManager.GetObject("linea_vertical_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_vertical_celeste {
            get {
                object obj = ResourceManager.GetObject("linea_vertical_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_vertical_morado {
            get {
                object obj = ResourceManager.GetObject("linea_vertical_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_vertical_naranja {
            get {
                object obj = ResourceManager.GetObject("linea_vertical_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_vertical_negra {
            get {
                object obj = ResourceManager.GetObject("linea_vertical_negra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_vertical_negra1 {
            get {
                object obj = ResourceManager.GetObject("linea_vertical_negra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_vertical_rojo {
            get {
                object obj = ResourceManager.GetObject("linea_vertical_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linea_vertical_verde {
            get {
                object obj = ResourceManager.GetObject("linea_vertical_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_abajo_izquierda_amarilla {
            get {
                object obj = ResourceManager.GetObject("lineaD_abajo_izquierda_amarilla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_abajo_izquierda_celeste {
            get {
                object obj = ResourceManager.GetObject("lineaD_abajo_izquierda_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_abajo_izquierda_morado {
            get {
                object obj = ResourceManager.GetObject("lineaD_abajo_izquierda_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_abajo_izquierda_naranja {
            get {
                object obj = ResourceManager.GetObject("lineaD_abajo_izquierda_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_abajo_izquierda_negro {
            get {
                object obj = ResourceManager.GetObject("lineaD_abajo_izquierda_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_abajo_izquierda_negro1 {
            get {
                object obj = ResourceManager.GetObject("lineaD_abajo_izquierda_negro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_abajo_izquierda_rojo {
            get {
                object obj = ResourceManager.GetObject("lineaD_abajo_izquierda_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_abajo_izquierda_verde {
            get {
                object obj = ResourceManager.GetObject("lineaD_abajo_izquierda_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_arriba_izquierda_amarilla {
            get {
                object obj = ResourceManager.GetObject("lineaD_arriba_izquierda_amarilla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_arriba_izquierda_celeste {
            get {
                object obj = ResourceManager.GetObject("lineaD_arriba_izquierda_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_arriba_izquierda_morado {
            get {
                object obj = ResourceManager.GetObject("lineaD_arriba_izquierda_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_arriba_izquierda_naranja {
            get {
                object obj = ResourceManager.GetObject("lineaD_arriba_izquierda_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_arriba_izquierda_negro {
            get {
                object obj = ResourceManager.GetObject("lineaD_arriba_izquierda_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_arriba_izquierda_negro1 {
            get {
                object obj = ResourceManager.GetObject("lineaD_arriba_izquierda_negro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_arriba_izquierda_rojo {
            get {
                object obj = ResourceManager.GetObject("lineaD_arriba_izquierda_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lineaD_arriba_izquierda_verde {
            get {
                object obj = ResourceManager.GetObject("lineaD_arriba_izquierda_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_relleno_amarillo {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_relleno_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_relleno_celeste {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_relleno_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_relleno_morado {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_relleno_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_relleno_naranja {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_relleno_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_relleno_negro {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_relleno_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_relleno_rojo {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_relleno_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_relleno_verde {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_relleno_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_vacio_amarillo {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_vacio_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_vacio_celeste {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_vacio_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_vacio_morado {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_vacio_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_vacio_naranja {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_vacio_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_vacio_negro {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_vacio_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_vacio_negro1 {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_vacio_negro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_vacio_rojo {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_vacio_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paralelogramo_vacio_verde {
            get {
                object obj = ResourceManager.GetObject("paralelogramo_vacio_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_relleno_amarillo {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_relleno_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_relleno_celeste {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_relleno_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_relleno_morado {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_relleno_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_relleno_naranja {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_relleno_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_relleno_negro {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_relleno_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_relleno_rojo {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_relleno_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_relleno_verde {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_relleno_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_vacio_amarillo {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_vacio_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_vacio_celeste {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_vacio_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_vacio_morado {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_vacio_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_vacio_naranja {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_vacio_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_vacio_negro {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_vacio_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_vacio_negro1 {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_vacio_negro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_vacio_rojo {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_vacio_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectaungulo_vacio_verde {
            get {
                object obj = ResourceManager.GetObject("rectaungulo_vacio_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_relleno_amarillo {
            get {
                object obj = ResourceManager.GetObject("rombo_relleno_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_relleno_celeste {
            get {
                object obj = ResourceManager.GetObject("rombo_relleno_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_relleno_morado {
            get {
                object obj = ResourceManager.GetObject("rombo_relleno_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_relleno_naranja {
            get {
                object obj = ResourceManager.GetObject("rombo_relleno_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_relleno_negro {
            get {
                object obj = ResourceManager.GetObject("rombo_relleno_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_relleno_rojo {
            get {
                object obj = ResourceManager.GetObject("rombo_relleno_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_relleno_verde {
            get {
                object obj = ResourceManager.GetObject("rombo_relleno_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_vacio_amarillo {
            get {
                object obj = ResourceManager.GetObject("rombo_vacio_amarillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_vacio_celeste {
            get {
                object obj = ResourceManager.GetObject("rombo_vacio_celeste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_vacio_morado {
            get {
                object obj = ResourceManager.GetObject("rombo_vacio_morado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_vacio_naranja {
            get {
                object obj = ResourceManager.GetObject("rombo_vacio_naranja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_vacio_negro {
            get {
                object obj = ResourceManager.GetObject("rombo_vacio_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_vacio_negro1 {
            get {
                object obj = ResourceManager.GetObject("rombo_vacio_negro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_vacio_rojo {
            get {
                object obj = ResourceManager.GetObject("rombo_vacio_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rombo_vacio_verde {
            get {
                object obj = ResourceManager.GetObject("rombo_vacio_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
